// lib/emailStages.js
// Single source of truth for every automated Academy email stage.
// Consumed by admin UI, emails-stats, and triggered-email-webhook.

const TRIAL_WEBHOOK = "/api/admin/trial-expiry-reminder-webhook";
const REWIND_WEBHOOK = "/api/admin/lapsed-trial-reengagement-webhook";
const TRIGGER_WEBHOOK = "/api/admin/triggered-email-webhook";

const SCHEDULE_LONDON_9 = {
  cadence: "daily",
  timeOfDay: "09:00 Europe/London",
  mechanism: "Vercel Cron (08:00 + 09:00 UTC with London-hour gate)",
};

const EMAIL_STAGES = [
  {
    key: "trial-welcome-nudge",
    shortLabel: "Trial D2·A",
    displayName: "Trial day ~2 · Welcome nudge (0 modules)",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    sentBy: "triggered-email-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Active trial · London day 2 · modulesOpened === 0",
    trigger: {
      audience: "active_trial",
      minTrialDay: 2,
      maxTrialDay: 2,
      modulesOpenedEq: 0,
      mutuallyExclusiveWith: ["trial-progress-nudge"],
    },
    description:
      "Gentle first-step nudge for trialists who have not opened any modules. Mutually exclusive with progress nudge.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "trial-welcome-nudge", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "trial-welcome-nudge", sendEmail: "true" } },
  },
  {
    key: "trial-progress-nudge",
    shortLabel: "Trial D2·B",
    displayName: "Trial day ~2–3 · Progress nudge (≥1 module, quiet ≥1d)",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    sentBy: "triggered-email-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Active trial · day 2–3 · modulesOpened ≥ 1 · daysSinceLastLogin ≥ 1",
    trigger: {
      audience: "active_trial",
      minTrialDay: 2,
      maxTrialDay: 3,
      modulesOpenedMin: 1,
      minDaysSinceLastLogin: 1,
      mutuallyExclusiveWith: ["trial-welcome-nudge"],
    },
    description: "Progress variant for trialists who started but have gone quiet.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "trial-progress-nudge", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "trial-progress-nudge", sendEmail: "true" } },
  },
  {
    key: "trial-stalled",
    shortLabel: "Trial D5",
    displayName: "Trial day ~5 · Stalled (quiet ≥3d)",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    sentBy: "triggered-email-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Active trial · day 4–6 · daysSinceLastLogin ≥ 3",
    trigger: {
      audience: "active_trial",
      minTrialDay: 4,
      maxTrialDay: 6,
      minDaysSinceLastLogin: 3,
    },
    description: "Supportive mid-trial re-engagement when a member goes quiet.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "trial-stalled", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "trial-stalled", sendEmail: "true" } },
  },
  {
    key: "day-minus-7",
    shortLabel: "Day -7",
    displayName: "Day -7 · Mid-trial reminder",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    legacyStats: true,
    daysFromTrialExpiry: -7,
    sentBy: "trial-expiry-reminder-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Active trial · trial day 7 (timer + existing template)",
    description: "Halfway through the 14-day trial. Live — existing webhook.",
    preview: { webhook: TRIAL_WEBHOOK, params: { daysAhead: 7, forceDaysUntilExpiry: 7, sendEmail: "false" } },
    testSend: { webhook: TRIAL_WEBHOOK, params: { daysAhead: 7, forceDaysUntilExpiry: 7, sendEmail: "true" } },
  },
  {
    key: "day-minus-1",
    shortLabel: "Day -1",
    displayName: "Day -1 · Final-day reminder",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    legacyStats: true,
    daysFromTrialExpiry: -1,
    sentBy: "trial-expiry-reminder-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Active trial · final day (timer + existing template)",
    description: "Last day of the free trial. Live — existing webhook.",
    preview: { webhook: TRIAL_WEBHOOK, params: { daysAhead: 1, forceDaysUntilExpiry: 1, sendEmail: "false" } },
    testSend: { webhook: TRIAL_WEBHOOK, params: { daysAhead: 1, forceDaysUntilExpiry: 1, sendEmail: "true" } },
  },
  {
    key: "day-plus-7",
    shortLabel: "Day +7",
    displayName: "Day +7 · SAVE20 offer",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    legacyStats: true,
    daysFromTrialExpiry: 7,
    sentBy: "trial-expiry-reminder-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Expired · not converted · day +7 (timer + SAVE20)",
    description: "7 days after trial expiry. SAVE20 offer. Live — existing webhook.",
    preview: { webhook: TRIAL_WEBHOOK, params: { daysAhead: -7, forceDaysUntilExpiry: -7, sendEmail: "false" } },
    testSend: { webhook: TRIAL_WEBHOOK, params: { daysAhead: -7, forceDaysUntilExpiry: -7, sendEmail: "true" } },
  },
  {
    key: "day-plus-20",
    shortLabel: "Day +20",
    displayName: "Day +20 · REWIND20 attempt 1",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    legacyStats: true,
    daysFromTrialExpiry: 20,
    sentBy: "lapsed-trial-reengagement-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Expired · not converted · ≥20d · win-back #1",
    trigger: { audience: "expired_trial", minDaysSinceExpiry: 20, maxDaysSinceExpiry: 40, exactSendCount: 0 },
    description: "First REWIND20 outreach. Live — lapsed-trial-reengagement-webhook.",
    preview: { webhook: REWIND_WEBHOOK, params: { sendEmail: "false" } },
    testSend: { webhook: REWIND_WEBHOOK, params: { sendEmail: "true" } },
  },
  {
    key: "day-plus-30",
    shortLabel: "Day +30",
    displayName: "Day +30 · REWIND20 attempt 2",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    legacyStats: true,
    daysFromTrialExpiry: 30,
    sentBy: "lapsed-trial-reengagement-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Expired · not converted · ≥30d · win-back #2",
    trigger: { audience: "expired_trial", minDaysSinceExpiry: 30, maxDaysSinceExpiry: 55, exactSendCount: 1 },
    description: "Second REWIND20 outreach. Live — lapsed-trial-reengagement-webhook.",
    preview: { webhook: REWIND_WEBHOOK, params: { sendEmail: "false" } },
    testSend: { webhook: REWIND_WEBHOOK, params: { sendEmail: "true" } },
  },
  {
    key: "day-plus-60",
    shortLabel: "Day +60",
    displayName: "Day +60 · REWIND20 final attempt",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    legacyStats: true,
    daysFromTrialExpiry: 60,
    sentBy: "lapsed-trial-reengagement-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Expired · not converted · ≥60d · win-back #3",
    trigger: { audience: "expired_trial", minDaysSinceExpiry: 60, maxDaysSinceExpiry: 89, exactSendCount: 2 },
    description: "Third REWIND20 outreach. Live — lapsed-trial-reengagement-webhook.",
    preview: { webhook: REWIND_WEBHOOK, params: { sendEmail: "false" } },
    testSend: { webhook: REWIND_WEBHOOK, params: { sendEmail: "true" } },
  },
  {
    key: "day-plus-90",
    shortLabel: "Day +90",
    displayName: "Day +90 · Final win-back",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    sentBy: "triggered-email-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Expired · not converted · ≥90d · long-lapsed",
    trigger: { audience: "expired_trial", minDaysSinceExpiry: 90, maxDaysSinceExpiry: 180, exactSendCount: 3 },
    description: "Final win-back rung — then exhaustion/suppression. Live — triggered-email-webhook.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "day-plus-90", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "day-plus-90", sendEmail: "true" } },
  },
  {
    key: "paid-quiet",
    shortLabel: "Paid 30d",
    displayName: "Paid · Quiet 30–44d (ladder rung 1)",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    sentBy: "triggered-email-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Active paid · daysSinceLastLogin 30–44",
    trigger: { audience: "paid", minDaysSinceLastLogin: 30, maxDaysSinceLastLogin: 44 },
    description: "First rung of paid quiet escalation ladder.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-quiet", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-quiet", sendEmail: "true" } },
  },
  {
    key: "paid-quiet-45",
    shortLabel: "Paid 45d",
    displayName: "Paid · Quiet 45–59d (ladder rung 2)",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    sentBy: "triggered-email-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Active paid · daysSinceLastLogin 45–59",
    trigger: { audience: "paid", minDaysSinceLastLogin: 45, maxDaysSinceLastLogin: 59 },
    description: "Second rung of paid quiet escalation ladder.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-quiet-45", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-quiet-45", sendEmail: "true" } },
  },
  {
    key: "paid-quiet-60",
    shortLabel: "Paid 60d",
    displayName: "Paid · Quiet 60–89d (ladder rung 3)",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    sentBy: "triggered-email-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Active paid · daysSinceLastLogin 60–89",
    trigger: { audience: "paid", minDaysSinceLastLogin: 60, maxDaysSinceLastLogin: 89 },
    description: "Third rung of paid quiet escalation ladder.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-quiet-60", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-quiet-60", sendEmail: "true" } },
  },
  {
    key: "paid-quiet-90",
    shortLabel: "Paid 90d",
    displayName: "Paid · Quiet 90d+ (ladder rung 4 · final)",
    enabled: true,
    testModeOnly: false,
    cronEnabled: true,
    sentBy: "triggered-email-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Active paid · daysSinceLastLogin ≥ 90 (final nudge)",
    trigger: { audience: "paid", minDaysSinceLastLogin: 90 },
    description: "Final rung of paid quiet escalation — no further paid-quiet emails after this.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-quiet-90", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-quiet-90", sendEmail: "true" } },
  },
  {
    key: "paid-badge-earned",
    shortLabel: "Badge earned",
    displayName: "Paid · Badge earned celebration",
    enabled: false,
    testModeOnly: false,
    cronEnabled: false,
    sentBy: "triggered-email-webhook",
    schedule: { cadence: "event-driven (scaffold)", timeOfDay: "—", mechanism: "Disabled until event hook exists" },
    triggerSummary: "Active paid · badge threshold crossed (event-driven scaffold)",
    trigger: { audience: "paid", eventDriven: true },
    description: "Celebrate a newly earned badge. Event-driven scaffold — disabled.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-badge-earned", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-badge-earned", sendEmail: "true" } },
  },
  {
    key: "paid-milestone",
    shortLabel: "Milestone",
    displayName: "Paid · Progress milestone",
    enabled: false,
    testModeOnly: false,
    cronEnabled: false,
    sentBy: "triggered-email-webhook",
    schedule: { cadence: "event-driven (scaffold)", timeOfDay: "—", mechanism: "Disabled" },
    triggerSummary: "Active paid · module milestone (25/50/100% scaffold)",
    trigger: { audience: "paid", eventDriven: true },
    description: "Encouragement at progress milestones. Scaffold disabled.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-milestone", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-milestone", sendEmail: "true" } },
  },
  {
    key: "paid-renewal-soon",
    shortLabel: "Renewal",
    displayName: "Paid · Renewal approaching",
    enabled: false,
    testModeOnly: false,
    cronEnabled: false,
    sentBy: "triggered-email-webhook",
    schedule: SCHEDULE_LONDON_9,
    triggerSummary: "Active paid · renewal within N days (scaffold)",
    trigger: { audience: "paid", renewalWithinDays: 30 },
    description: "Renewal reminder with progress recap. Scaffold disabled.",
    preview: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-renewal-soon", sendEmail: "false" } },
    testSend: { webhook: TRIGGER_WEBHOOK, params: { stageKey: "paid-renewal-soon", sendEmail: "true" } },
  },
];

const TRIGGER_STAGES = EMAIL_STAGES.filter((s) => s.trigger && !s.legacyStats);

function getStageByKey(key) {
  return EMAIL_STAGES.find((s) => s.key === key) || null;
}

function listCronEnabledTriggerStages() {
  return EMAIL_STAGES.filter((s) => s.cronEnabled && s.sentBy === "triggered-email-webhook");
}

module.exports = {
  EMAIL_STAGES,
  TRIGGER_STAGES,
  TRIAL_WEBHOOK,
  REWIND_WEBHOOK,
  TRIGGER_WEBHOOK,
  getStageByKey,
  listCronEnabledTriggerStages,
};
